name: jeras
description: jeras application
version: 1.2.9+72

environment:
  sdk: ">=3.0.0 <4.0.0"



dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.18.0
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_database: ^10.3.6
  simple_gradient_text: ^1.3.0
  lottie: ^2.7.0
  firebase_pagination: ^3.0.1
  firebase_storage: ^11.5.3
  firebase_analytics: ^10.7.2
  firebase_dynamic_links: ^5.4.6
  firebase_messaging: ^14.7.6
  #jitsi_meet_wrapper: ^0.2.0+1
  flutter_file_downloader: ^1.1.4
  open_file: ^3.3.2
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.2.0
  flutter_share: ^2.0.0
  share_plus:
  flutter_svg: ^2.0.9
  hexcolor: ^3.0.1
#  flutter_webrtc: ^0.9.36
  #flutter_callkeep: ^0.3.3
  font_awesome_flutter: ^10.6.0
  inject_js: ^2.0.0
  web_ffi: ^0.7.2
  google_fonts: ^4.0.4
  http: ^0.13.6
  universal_html: ^2.2.4
  image_cropper: ^4.0.1
  image_picker: ^1.0.1
  path_provider: ^2.1.1
  flutter_foreground_plugin:
    git:
      url: https://github.com/jja08111/flutter_foreground_service_plugin.git
      ref: 8a09c7b0aeb9d31204147fe6ee126c8a52471e3a
  flutter_background: ^1.2.0
  # callkeep: ^0.3.3
  shared_preferences: ^2.2.2
  smooth_star_rating_null_safety: ^1.0.4+2
  uuid: ^4.2.1
  #flutter_credit_card: ^4.0.1
  intl_phone_field:
  intl_phone_number_input:
    git:
      url: https://github.com/loaidev64/intl_phone_number_input.git
      ref: develop
  cached_network_image: ^3.3.0
  webview_flutter: ^3.0.4
  day_picker: ^2.2.0
  pointer_interceptor: ^0.9.3+7
  permission_handler: ^11.1.0
  flutter_image_slideshow: ^0.1.6
  stop_watch_timer: ^3.0.2
  readmore: ^2.2.0
  multi_select_flutter: ^4.1.3
  url_launcher: ^6.2.1
  cloud_functions: ^4.5.6
  package_info_plus:
  sms_autofill: ^2.3.0
  pdf: ^3.10.6
  shimmer: ^3.0.0
  flutter_colorpicker: ^1.0.3
  linkwell: ^2.0.6
  firebase_crashlytics: ^3.4.6
  #wakelock: ^0.4.0
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe:
  hijri_picker: ^3.0.0
  modal_bottom_sheet: ^2.1.2
  fluttertoast: ^8.2.4
  sizer: ^2.0.15
  appsflyer_sdk: ^6.12.2
  record_mp3: ^3.0.0
  #fixnum: ^1.1.0
  fluro: ^2.0.5
  #flutter_ringtone_player: ^3.2.0
  timelines: ^0.1.0
  audioplayers: ^5.2.1
  video_player: ^2.8.2
  flutter_slidable: ^3.0.1
  #chip_list: ^2.4.3+8
  #build_runner: ^2.4.6
  voice_message_package: ^2.1.2
  pinput: ^3.0.1
  dropdown_button2: ^1.8.5
  timeago: ^3.6.0
  #  flutter_screenutil: ^5.8.4
  agora_rtc_engine: ^5.3.1
  #whiteboard: ^0.0.2
  country_picker:
    git:
      url: https://github.com/3khaled3/flutter_country_picker_for_jeras.git
  syncfusion_flutter_sliders: ^23.2.6
  group_radio_button: ^1.3.0
  draggable_fab: ^0.1.4
  record: ^5.0.1
  #ffi: ^2.0.2
  file_picker: ^6.1.1
  #device_info_plus: ^9.1.1
  #  flutter_zoom_videosdk: ^1.7.0
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.3
  dart_jsonwebtoken: ^2.12.1
  shared_value: ^3.0.0
  events_emitter: ^0.5.2
  #flutter_callkit_incoming: ^2.0.0+1
  app_settings: ^5.1.1
  checkbox_grouped: ^2.0.0
  another_flushbar: ^1.12.30
  rating_dialog: ^2.0.4
  in_app_review: ^2.0.8
  auto_size_text: ^3.0.0
  jitsi_meet_flutter_sdk: ^0.1.9
  showcaseview: ^2.0.3
  im_stepper: ^1.0.1+1
  dartz: ^0.10.1
  conditional_builder_null_safety: ^0.0.6
  audio_waveforms: ^1.0.4
  flutter_callkit_incoming:
    path: packages/flutter_callkit_incoming-master
  step_progress_indicator: ^1.0.2
  #flutter_callkeep: ^0.3.3

#dependency_overrides:
#  web: ^0.4.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1


  # flutter_icons:
  #   android: true
  #   ios: true
  #   image_path: "assets/icons/logo.png"
  #   background_color: "0xFF7b6c94"

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/zoom/icons/
    - assets/fonts/
    - assets/OpenSans-Regular.ttf
    - assets/images/
    - assets/jeras_icons/
    - assets/call/
    - assets/banners/
    - assets/sound/
    - assets/sound/emojisound/
    - assets/lotifile/
    - assets/lotifile/emojies/
    - lib/lang/

  fonts:
    - family: elMessiri
      fonts:
        - asset: assets/fonts/elMessiri-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Arial
      fonts:
        - asset: assets/fonts/Arial.ttf


    - family: Bukra
      fonts:
        - asset: assets/fonts/29LT Bukra Bold.otf

    - family: Ithra
      fonts:
        - asset: assets/fonts/alfont_com_Ithra-Bold.ttf
    - family: Ithralight
      fonts:
        - asset: assets/fonts/Ithra-Light.ttf
    - family: Montserratbold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserratmedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserratsemibold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Ithra_Bold
      fonts:
        - asset: assets/fonts/Ithra-Bold.ttf
    - family: NotoKufiArabic-Regular
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
    - family: NotoKufiArabic-SemiBold
      fonts:
        - asset: assets/fonts/NotoKufiArabic-SemiBold.ttf
    - family: NotoKufiArabic-Medium
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Medium.ttf



#flutter_native_splash:
#  color: "#796d91"
#  image: assets/applicationIcons/splach.jpg
#  color_dark: "#796D91"
#  image_dark: assets/applicationIcons/splach.jpg
#  android_12:
#    image: assets/applicationIcons/splach.jpg
#    icon_background_color: "#796D91"
#    image_dark: assets/applicationIcons/splach.jpg
#    icon_background_color_dark: "#796D91"
#
#  web: true
#
#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/icons/logo.png"
#  # min_sdk_android: 21 # android min sdk min:16, default 21
#  background_color: "#7b6c94"
#  web:
#    generate: true
#    image_path: "assets/images/favion.png"
#    background_color: "#7b6c94"
#    theme_color: "#7b6c94"
#  windows:
#    generate: true
#    image_path: "assets/images/favicon.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "assets/images/favion.png"